### ISSUE TITLE
To many any in codebase

### ISSUE THREAD

**Issue by mlodyoskar** [whit33y/blog-app#2]
Try not to use `any` at all cost. 

⬇ Here, you can just use type: React.ReactNode, or JSX.Element, read about differences between these two, and choose which fits you well.
https://github.com/whit33y/blog-app/blob/1671f3a854410f412b7cf65ec6bfa295b398fb50/src/components/ProtectedRoute.tsx#L4

⬇ About the next two - if you want to type from submit event you can use `React.FormEvent<HTMLFormElement>`. Or just better idea would be to use library which does all this for you e.g. [RHF](https://react-hook-form.com/)
https://github.com/whit33y/blog-app/blob/1671f3a854410f412b7cf65ec6bfa295b398fb50/src/pages/Login.tsx#L13
https://github.com/whit33y/blog-app/blob/1671f3a854410f412b7cf65ec6bfa295b398fb50/src/pages/Signup.tsx#L14
⬇ For this problem console.log what comes back from API and type it this way
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/components/RenderPostHome.tsx#L10-L12

**Comment by whit33y** [comment]
Project is now free of 'any' types
