### ISSUE TITLE
Unnecessary file copying while creating new posts category

### ISSUE THREAD

**Issue by mlodyoskar** [whit33y/blog-app#3]
As I can see you use different files to render posts about IT, Lifestyle, and any other category. Why you do this way? Now for every new category you have to create a new file, which looks almost the same as the others.

I suggest you have one component to render all categories. So create a generic component for listing all posts, and then based on route do the request to the API, and render that.

**Comment by whit33y** [comment]
Problem solved, now there is one components that render all categories. Thanks for your feedback! 💜

**Comment by mlodyoskar** [comment]
Great job on that. However, I still see you are using different pages for different categories. Try to make generic page.

This will probably need some changes to your current routing system

**Comment by whit33y** [comment]
Problem fixed in this commit
https://github.com/whit33y/blog-app/commit/cf6a5f2647cc5fa1598ee45512b46e7718718473
