### ISSUE TITLE
Add React-Query to project for better cache and to avoid fetching in useEffect

### ISSUE THREAD

**Issue by mlodyoskar** [whit33y/blog-app#4]
As in the title, I highely suggest you to use caching library like [ReactQuery](https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/). Fetching in useEffect is not recommended.

**Comment by whit33y** [comment]
React-querry added. Thanks for help G ✋

**Comment by mlodyoskar** [comment]
Changed in #16
