### ISSUE TITLE
Some minor this that can be improved

### ISSUE THREAD

**Issue by mlodyoskar** [whit33y/blog-app#6]
⬇ I guess this should be extracted from component to hook.
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/components/RenderAddPost.tsx#L17-L23

⬇You can simply disable first option so user can't check it : [Example](https://stackoverflow.com/questions/22033922/how-to-show-disable-html-select-option-in-by-default#:~:text=386-,use,-%3Coption%20selected)
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/components/RenderAddPost.tsx#L49-L57

Also, it would be great if those select options would come from API, so it would be simpler to add new category in db, not files.

⬇ Almost every input should have `<label>` tag for accessibility reasons. People with screen readers whould't know what they should put in this input.
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/components/RenderAddPost.tsx#L32-L35

⬇ You have tailwind base classes imported in two places: 
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/App.css
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/index.css

Just keep it in one place 👌

⬇ You can change this file to typescript, and a good practise is to make sure that your .env variables are set: [example](https://github.com/mlodyoskar/PublishIT/blob/bed97a5a8106300958633998d0a796fc543fd77f/src/supabase.ts)
https://github.com/whit33y/blog-app/blob/b860d3836497d77db42a6a63ba4d1b418a73c0f8/src/supabase.js

**Comment by whit33y** [comment]
Minor issues improved

**Comment by whit33y** [comment]
Minor issues improved
